name: Redis4Cats
baseurl: ''
description: Redis client for Cats Effect & Fs2
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.9.1
org: Redis client for Cats Effect & Fs2
markdown: kramdown
